const allCookies = [
  {
    domain: '.chat.zalo.me',
    expirationDate: 1612840020.297604,
    hostOnly: false,
    httpOnly: true,
    name: 'zpw_sek',
    path: '/',
    sameSite: 'unspecified',
    secure: true,
    session: false,
    storeId: '0',
    value:
      '1FX_.239985360.a0.tcF1rxCyxcfZtgDaaZpkQiWUYm6H1imorL_UFFjTlIA1TDWdrtA-ADqFXZho0TD8pbiRbg37As0aFQB4XsFhMG',
    id: 1,
  },
  {
    domain: '.chat.zalo.me',
    expirationDate: 1612840012.624085,
    hostOnly: false,
    httpOnly: true,
    name: 'zpw_sekm',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'YkkA.239985360.107.BT9XH-k0jiexOll4ve2sofxpqxZPiu_pqxM5_DldGpRuUtF0V84mfzZVjie',
    id: 2,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1659496013.352071,
    hostOnly: false,
    httpOnly: false,
    name: '__zi',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      '3000.SSZzejyD6zOgdh2mtnLQWYQN_RAG01ICFjIXe9fEM8uzaEIgd4HNXdIIvwFNH526Uf7ahJ4v.1',
    id: 3,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1659496013.352134,
    hostOnly: false,
    httpOnly: false,
    name: '__zi-legacy',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value:
      '3000.SSZzejyD6zOgdh2mtnLQWYQN_RAG01ICFjIXe9fEM8uzaEIgd4HNXdIIvwFNH526Uf7ahJ4v.1',
    id: 4,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1597374412.806254,
    hostOnly: false,
    httpOnly: false,
    name: '_zlang',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: 'vn',
    id: 5,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1597460818.079824,
    hostOnly: false,
    httpOnly: true,
    name: 'app.event.zalo.me',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: '7783454124881528205',
    id: 6,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1660360025,
    hostOnly: false,
    httpOnly: false,
    name: 'fpsend',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: '147897',
    id: 7,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1628741894.806074,
    hostOnly: false,
    httpOnly: true,
    name: 'zpsid',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      '60M4.239985360.61.QdcuzfHzoJT4duGvc7t9D-4EkmMdHF0FeKx_1_E8DIGfnKrObVka1CjzoJS',
    id: 8,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1628741894.80618,
    hostOnly: false,
    httpOnly: true,
    name: 'zpsidleg',
    path: '/',
    sameSite: 'unspecified',
    secure: true,
    session: false,
    storeId: '0',
    value:
      '60M4.239985360.61.QdcuzfHzoJT4duGvc7t9D-4EkmMdHF0FeKx_1_E8DIGfnKrObVka1CjzoJS',
    id: 9,
  },
];

const authCookies = allCookies.filter(i =>
  ['zpw_sek', 'zpw_sekm', 'zpsid'].includes(i.name)
);

module.exports = authCookies;
