const allCookies = [
  {
    domain: '.chat.zalo.me',
    expirationDate: 1607407280.039248,
    hostOnly: false,
    httpOnly: true,
    name: 'zpw_sek',
    path: '/',
    sameSite: 'unspecified',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'wWeY.239985360.a0.x5TNnsihDdsxoNjpIYisVH09KnP94HGw0de5105lKnuVPW8n16DU2WrWRnWw5WjV5ap3WNXGmxwmAfMrYdKkim',
    id: 1,
  },
  {
    domain: '.chat.zalo.me',
    expirationDate: 1607407268.745436,
    hostOnly: false,
    httpOnly: true,
    name: 'zpw_sekm',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'F7Pw.239985360.89.XAH-HAbrz3zvbxanf7NqFzm6aKsRHiq6aK372PaI0SEw3W7ySdHNzqWhz3y',
    id: 2,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1654063269.820492,
    hostOnly: false,
    httpOnly: false,
    name: '__zi',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      '3000.SSZzejyD6zOgdh2mtnLQWYQN_RAG01ICFjIXe9fEM8uzaEIgd4HNXdIIvwFHHb28TPNbf3Cm.1',
    id: 3,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1654063269.820601,
    hostOnly: false,
    httpOnly: false,
    name: '__zi-legacy',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value:
      '3000.SSZzejyD6zOgdh2mtnLQWYQN_RAG01ICFjIXe9fEM8uzaEIgd4HNXdIIvwFHHb28TPNbf3Cm.1',
    id: 4,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1591941668.90368,
    hostOnly: false,
    httpOnly: false,
    name: '_zlang',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: 'vn',
    id: 5,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1592028074.753947,
    hostOnly: false,
    httpOnly: true,
    name: 'app.event.zalo.me',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: '7783454124881528205',
    id: 6,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1654927261,
    hostOnly: false,
    httpOnly: false,
    name: 'fpsend',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: '147394',
    id: 7,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1623391267.903576,
    hostOnly: false,
    httpOnly: true,
    name: 'zpsid',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'SwJb.239985360.43.rmle2MK_E7MrtNLxQJyuTH1CIaTM1W5DK0mEHGBAn6QNl_DKP9pmb3i_E7K',
    id: 8,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1623391267.903631,
    hostOnly: false,
    httpOnly: true,
    name: 'zpsidleg',
    path: '/',
    sameSite: 'unspecified',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'SwJb.239985360.43.rmle2MK_E7MrtNLxQJyuTH1CIaTM1W5DK0mEHGBAn6QNl_DKP9pmb3i_E7K',
    id: 9,
  },
];

const authCookies = allCookies.filter(i =>
  ['zpw_sek', 'zpw_sekm', 'zpsid'].includes(i.name)
);

module.exports = authCookies;
