const allCookies = [
  {
    domain: '.chat.zalo.me',
    expirationDate: 1668156250,
    hostOnly: false,
    httpOnly: false,
    name: '_ga',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: 'GA1.3.764884383.1601257535',
    id: 1,
  },
  {
    domain: '.chat.zalo.me',
    expirationDate: 1605170650,
    hostOnly: false,
    httpOnly: false,
    name: '_gid',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: 'GA1.3.1885894709.1605000657',
    id: 2,
  },
  {
    domain: '.chat.zalo.me',
    expirationDate: 1620711849.542684,
    hostOnly: false,
    httpOnly: true,
    name: 'zpw_sek',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'GF2B.239985360.a0.-UDi9Pf4nn9AfeeSkqJ74k5cedcuVkLv-H6CSwmFx5slCAD-od6YOCbpdNlzUVemvoCoxj7tlWzkHOGcCHi-V0',
    id: 3,
  },
  {
    domain: '.chat.zalo.me',
    expirationDate: 1620607556.918538,
    hostOnly: false,
    httpOnly: true,
    name: 'zpw_sekm',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'UhZD.239985360.121.7drW-s3wFR2m672-RVezi1M9MC9IoGI9MCyEXb2To4mhIKIjbFj-XCkbFR0',
    id: 4,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1667292245.196133,
    hostOnly: false,
    httpOnly: false,
    name: '__zi',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      '3000.SSZzejyD6zOgdh2mtnLQWYQN_RAG01ICFjIXe9fEM8uzaEIgd4HNXdIIvAhLHLI3T9VdhJGo.1',
    id: 5,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1667292245.196189,
    hostOnly: false,
    httpOnly: false,
    name: '__zi-legacy',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value:
      '3000.SSZzejyD6zOgdh2mtnLQWYQN_RAG01ICFjIXe9fEM8uzaEIgd4HNXdIIvAhLHLI3T9VdhJGo.1',
    id: 6,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1668156250,
    hostOnly: false,
    httpOnly: false,
    name: '_ga',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: 'GA1.2.764884383.1601257535',
    id: 7,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1605170650,
    hostOnly: false,
    httpOnly: false,
    name: '_gid',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: 'GA1.2.1885894709.1605000657',
    id: 8,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1605170643.989819,
    hostOnly: false,
    httpOnly: false,
    name: '_zlang',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: 'vn',
    id: 9,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1605257049.522551,
    hostOnly: false,
    httpOnly: true,
    name: 'app.event.zalo.me',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: '7783454124881528205',
    id: 10,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1668156257,
    hostOnly: false,
    httpOnly: false,
    name: 'fpsend',
    path: '/',
    sameSite: 'unspecified',
    secure: false,
    session: false,
    storeId: '0',
    value: '148618',
    id: 11,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1636591555.989696,
    hostOnly: false,
    httpOnly: true,
    name: 'zpsid',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'Uu_4.239985360.74.YlvcVeVvshDN6vUzY_dQi_AAg86qmEEBiihiW-0C9lWq4livXhlk6DZvshC',
    id: 12,
  },
  {
    domain: '.zalo.me',
    expirationDate: 1636591555.989771,
    hostOnly: false,
    httpOnly: true,
    name: 'zpsidleg',
    path: '/',
    sameSite: 'unspecified',
    secure: true,
    session: false,
    storeId: '0',
    value:
      'Uu_4.239985360.74.YlvcVeVvshDN6vUzY_dQi_AAg86qmEEBiihiW-0C9lWq4livXhlk6DZvshC',
    id: 13,
  },
];

const authCookies = allCookies.filter(i =>
  ['zpw_sek', 'zpw_sekm', 'zpsid'].includes(i.name)
);

module.exports = authCookies;
